spring.application.name=CustomerTranscationCal
server.port=8081

# Enable the H2 Console
spring.h2.console.enabled=true

# Database Connection Settings
#spring.datasource.url=jdbc:h2:mem:customerDB
spring.datasource.url=jdbc:h2:file:./data/customerTransactionDB
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=raushan
spring.datasource.password=pds4567@

# Show SQL queries in the console (helpful for debugging)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format-sql=true
spring.jpa.hibernate.ddl-auto=update

# Ignoring Extra Fields Coming in JSON payloads
spring.jackson.deserialization.fail-on-unknown-properties=true
